version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: flask-app
    CONTAINER_NAME: flask-container
    CLUSTER_NAME: MyECSCluster
    SERVICE_NAME: flask-service

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 381491832726.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=381491832726.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME
      - echo "Repository URI: $REPOSITORY_URI"
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=$COMMIT_HASH
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG ./app
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
